### ISSUE TITLE
Suggestion: Disable and enable certain hacks

### ISSUE THREAD

**Issue by Us3rNqmed** [steviebeenz/BubbleAnticheatReborn#12]
If you do /bubble hacks
It'll open a gui which shows types of hacks, 
in there you can enable and disable these modes so certain hacks wont be detected.

**Comment by steviebeenz** [comment]
I believe this may be already implemented, try /bubble on the latest version.

**Comment by steviebeenz** [comment]
@Us3rNqmed This is in the config file, if you need this in a UI, make another issue.
